- .nais/dev.yml
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/egress/config/EgressService.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/egress/token/unt/client/UsernameTokenClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/egress/token/unt/client/fssgw/FssGatewayUsernameTokenClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/egress/token/unt/client/fssgw/dto/UsernameTokenDto.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tp/TjenestepensjonService.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tp/api/TjenestepensjonController.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tp/api/dto/TjenestepensjonsforholdDto.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tp/client/TjenestepensjonClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tp/client/esb/EsbTjenestepensjonClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tp/client/esb/dto/EnvelopeDto.kt
- src/main/resources/application.properties
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/client/np/NorskPensjonPensjonsavtaleClientTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/mock/WebClientTest.java
- src/test/kotlin/no/nav/pensjon/kalkulator/mock/XmlMapperFactory.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/security/egress/token/unt/client/fssgw/FssGatewayUsernameTokenClientTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tp/TjenestepensjonServiceTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tp/api/TjenestepensjonControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tp/client/esb/EsbTjenestepensjonClientTest.kt
Henter tjenestepensjonsforhold fra tjenestebussen (SOAP-kall med UsernameToken-autentisering).
UsernameToken er web service-varianten av "Basic auth" (brukernavn+passord).
Brukernavnet er servicebruker `srvpselv`.
Passordet til servicebruker bør helst bare finnes i FSS (ikke i GCP). Derfor hentes UsernameToken fra FSS-gateway.
Responsen brukes nå bare til å sjekke om det finnes et TP-forhold. Dette brukes så i backend-API-et til å returnere
```
{
"harTjenestepensjonsforhold": true/false
}
```
på `GET api/tpo-medlemskap`
> PEK-78 Fetch TP-forhold from ESB

- src/main/kotlin/no/nav/pensjon/kalkulator/uttaksalder/UttaksalderService.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/uttaksalder/UttaksalderSpec.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/uttaksalder/api/dto/UttaksalderIngressSpecDto.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/uttaksalder/client/pen/map/PenUttaksalderMapper.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/uttaksalder/api/UttaksalderControllerTest.kt
[simulerAlderspensjonV1](https://pensjonskalkulator-backend.intern.dev.nav.no/swagger-ui/index.html#/simulering-controller/simulerAlderspensjonV1) har `simuleringstype` fra før. Greit å ha likt på tvers av controllere
> PEK-141 simuleringstype >> simuleringType

- .nais/deploy-prod.yml
Setter initielle verdier etter å se på stress-test minne og CPU-bruk i dev-miljø. Riktige verdier finner vi sannsynligvis etter offentliggjøring av appen. [https://grafana.nais.io/d/0Qx_7cA4k/pensjonskalkulator?orgId=...](https://grafana.nais.io/d/0Qx_7cA4k/pensjonskalkulator?orgId=1&var-datasource=dev-gcp&var-app=pensjonskalkulator-backend&var-namespace=pensjonskalkulator&var-interval=2m&from=1696971051772&to=1696974351288)
**Minne**
1GB initiell minne, 2GB limit: det ble brukt ca 1GB i gjennomsnitt i løpet av stresstesten, ved 2GB minne sleit poddene.
**CPU**
1 kjerne initiell, 2 kjerner - limit: 1 kjerne ble brukt ved spikes som backend klarte å fordøye, 2-3 kjerner var toppen før restart
`cpuThresholdPercentage: 70` - oppskalering ved 70% CPU-bruk (default 50)
> add resources and limits to prod instances

- src/main/kotlin/no/nav/pensjon/kalkulator/tech/web/WebClientConfig.kt
Det forbedrer kommunikasjonen en god del hvis det tar betydelig lengre tid å få svar fra PEN.
Antall på requester med 200 respons går opp og vi skyver flaskehalsen til PEN.
Usikker om det burde vært en separat webclient spesielt for PEN
> Add higher timeouts for webclient to wait for pen slow responses

- src/main/kotlin/no/nav/pensjon/kalkulator/simulering/SimulertAfpOffentlig.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/simulering/api/SimuleringController.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/simulering/api/dto/IngressSimuleringSpecV6.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/simulering/api/dto/SimuleringResultatV6.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/simulering/api/map/SimuleringMapperV6.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/simulering/client/pen/dto/PenSimuleringResultDto.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/api/OpenApiConfiguration.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/simulering/api/SimuleringControllerTest.kt
En ren kopi av V5. AFP Offentlig skal se sånn ut i V6 (som AfpPrivat):
```
"afpOffentlig": {
"afpOffentligListe": [
{
"beloep": 22056,
"alder": 67
}
]
}
```
> legg til simulerAlderspensjon V6 med AFP offentlig uten afpleverandørnavn

- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/FinnTjenestepensjonsforholdResponsDto.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/Tjenestepensjon.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/TjenestepensjonService.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/client/TjenestepensjonClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/client/tp/TpTjenestepensjonClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/client/tp/map/TpTjenestepensjonMapper.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/TjenestepensjonServiceTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/client/tp/TpTjenestepensjonClientTest.kt
`api/tjenestepensjon` gir ikke navn på tp-ordning
`api/tjenestepensjon/finnTjenestepensjonsforhold` gjør det samme, men gir navn
Vi sanerer bruk av api/tjenestepensjon når frontend flyttes over det nye endepunktet
> PEK-424 bytt endepunkt for å hente navn på tp-ordninger hvor bruker er medlem i

- .nais/deploy-dev.yml
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/PensjonsavtaleService.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/client/np/v3/NorskPensjonMockPensjonsavtaleClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/client/np/v3/NorskPensjonPensjonsavtaleClient.kt
- src/main/resources/application-local-ps.properties
- src/main/resources/application-local.properties
- src/main/resources/application.properties
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/PensjonsavtaleServiceTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/client/np/v3/NorskPensjonMockPensjonsavtaleClientTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/client/np/v3/NorskPensjonPensjonsavtaleClientTest.kt
Pensjonsavtalene lagres og hentes fra pensjon-testdata-facade:
[https://pensjon-testdata-facade.dev-fss-pub.nais.io/swagger-ui/index.html#/Pensjonsavtale/hentPensjonsavtaler](https://pensjon-testdata-facade.dev-fss-pub.nais.io/swagger-ui/index.html#/Pensjonsavtale/hentPensjonsavtaler)
Det utføres ingen simulering/beregning, kun henting av det som var lagret på forhånd.
Lagrede avtaler hentes, hvis feature toggle er aktivert: 
[https://pensjonskalkulator-unleash-web.iap.nav.cloud.nais.io/projects/default/features/mock-norsk-pensjon
](https://pensjonskalkulator-unleash-web.iap.nav.cloud.nais.io/projects/default/features/mock-norsk-pensjon
)
> PEK-468 legg til mockede pensjonsavtaler fra test miljø

- .nais/deploy-dev.yml
- .nais/deploy-prod.yml
- src/main/resources/application.properties
Etterlatte endrer navnet til appen sin. Med [service discovery](https://docs.nais.io/workloads/how-to/communication/) slipper man å gå via ingresser og forhåpentligvis slippe nettverksproblemer pga det.
[https://github.com/navikt/pensjon-etterlatte-saksbehandling/blob/main/apps/etterlatte-samordning-vedtak/.nais/prod-api.yaml](https://github.com/navikt/pensjon-etterlatte-saksbehandling/blob/main/apps/etterlatte-samordning-vedtak/.nais/prod-api.yaml)
> PEK-486 oppdater etterlatte-api appnavnet og ta i bruk service discovery

- .github/workflows/deploy.yaml
Det anbefales til å spesifisere truvy-db url for å unngå `TOOMANYREQUESTS` ved image scan
[https://nav-it.slack.com/archives/C5KUST8N6/p1730118311599129](https://nav-it.slack.com/archives/C5KUST8N6/p1730118311599129)
> unngå TOOMANYREQUESTS fra trivy mot OCI

- pom.xml
- src/test/kotlin/no/nav/pensjon/kalkulator/ansatt/api/AnsattControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/api/PensjonsavtaleControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/ekskludering/api/EkskluderingControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/omstillingsstoenad/api/OmstillingsstoenadOgGjenlevendeYtelseControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/opptjening/api/InntektControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/person/api/PersonControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/simulering/api/SimuleringControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/crypto/api/CryptoControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/status/StatusControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/toggle/api/FeatureToggleControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/api/TjenestepensjonControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/ufoere/api/UfoerepensjonControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/uttaksalder/api/UttaksalderControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/vedtak/api/VedtakControllerTest.kt
Erstatter `@MockBean`, som er _deprecated_ (ref . [Spring doc](https://docs.spring.io/spring-boot/api/java/org/springframework/boot/test/mock/mockito/MockBean.html)).
Bumper Kotlin og Unleash.
Angir også `kotlin.compiler.languageVersion` + `kotlin.compiler.apiVersion` (ref.  [PEN PR](https://github.com/navikt/pensjon-pen/pull/14366)).
> MockBean -> MockitoBean

- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/PensjonsavtaleSpec.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/api/PensjonsavtaleController.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/api/dto/PensjonsavtaleResultV3.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/api/dto/PensjonsavtaleSpecV3.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/api/map/PensjonsavtaleResultMapperV3.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/api/map/PensjonsavtaleSpecMapperV3.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/avtale/client/np/v3/map/NorskPensjonPensjonsavtaleMapper.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/PensjonsavtaleServiceTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/api/PensjonsavtaleControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/api/map/PensjonsavtaleResultMapperV3Test.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/api/map/PensjonsavtaleSpecMapperV3Test.kt
Utenlandsopphold er ikke relevant som input til Norsk Pensjons tjeneste for å hente pensjonsavtaler.
Derfor fjernes dette i V3 av endepunktet som skal brukes av frontend.
I tillegg endres to feltnavn:
- `harEpsPensjonsgivendeInntektOver2G` -> `epsHarInntektOver2G`
- `harEpsPensjon` -> `epsHarPensjon`
Dette for å få konsekvent navngivning i API-et.
V2 vil bli fjernet når frontend har gått over til V3.
> PEK-813 Pensjonsavtaler V3: No utenlandsopphold

- pom.xml
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/api/OpenApiConfiguration.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/ingress/impersonal/skjerming/client/nom/NomSkjermingClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/ingress/impersonal/skjerming/client/nom/NomSkjermingSpec.kt
Endring 1: Bruker POST i kall til 'skjermet' (se [Slack-melding](https://nav-it.slack.com/archives/CTN3BDUQ2/p1730286270363839) for bakgrunn).
Endring 2: Legger til `/api/v3/pensjonsavtaler` i API-dok (glemte dette i [PR 140](https://github.com/navikt/pensjonskalkulator-backend/pull/140)).
> PEK-829 Use POST in call to 'skjermet'

- .nais/deploy-dev.yml
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/api/OpenApiConfiguration.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/TjenestepensjonSimuleringService.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/TjenestepensjonSimuleringController.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/dto/IngressSimuleringOffentligTjenestepensjonSpecV2.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/dto/OffentligTjenestepensjonSimuleringsresultatDtoV2.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/map/TjenestepensjonSimuleringResultMapperV2.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/map/TjenestepensjonSimuleringSpecMapperV2.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/TjenestepensjonSimuleringClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/SimuleringOffentligTjenestepensjonSpecV2.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/TpSimuleringClient.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/dto/SimuleringOFTPSpecDto.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/map/TpSimuleringClientMapper.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/opptjening/FremtidigInntektV2ServiceTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/opptjening/FremtidigInntektV2UtilTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/opptjening/api/FremtidigInntektV2ControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/opptjening/api/map/FremtidigInntektV2MapperTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/TjenestepensjonSimuleringControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/TjenestepensjonSimuleringServiceTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/map/TjenestepensjonSimuleringResultMapperV2Test.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/map/TjenestepensjonSimuleringSpecMapperV2Test.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/TpSimuleringClientTest.kt
Mapping av Inntekter til fremtidige inntekter
0-inntekt kan starte fra:
1. uttaksdato for gradert uttak, hvis ingen inntekt ved siden av gradert og helt uttak
2. uttaksdato for helt uttak, hvis ingen inntekt ved siden av helt uttak etter inntekt ved siden av gradert uttak
3. en måned etter dato ved sluttalderen for inntekten ved siden av helt uttak
> Fremtidige inntekter i tjenestepensjon-simulering

- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/dto/OffentligTjenestepensjonSimuleringsresultatDtoV2.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/api/map/TjenestepensjonSimuleringResultMapperV2.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/OffentligTjenestepensjonSimuleringsresultat.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/dto/SimulerTjenestepensjonResponseDto.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/client/tpsimulering/map/TpSimuleringClientMapper.kt
Debug tjenstepensjon-simulering sammen med SPK
Eksempel på tilleggsopplysninger om request/response til SPK:
```
"serviceData": [
"Request: SPKSimulerTjenestepensjonRequest(personId=01810198296, uttaksListe=[Uttak(ytelseType=PAASLAG, fraOgMedDato=2065-01-01, uttaksgrad=null), Uttak(ytelseType=APOF2020, fraOgMedDato=2065-01-01, uttaksgrad=null), Uttak(ytelseType=OT6370, fraOgMedDato=2065-01-01, uttaksgrad=null), Uttak(ytelseType=SAERALDERSPAASLAG, fraOgMedDato=2065-01-01, uttaksgrad=null), Uttak(ytelseType=BTP, fraOgMedDato=2065-01-01, uttaksgrad=null)], fremtidigInntektListe=[FremtidigInntekt(aarligInntekt=380410, fraOgMedDato=2023-01-01), FremtidigInntekt(aarligInntekt=0, fraOgMedDato=2065-01-01)], aarIUtlandetEtter16=0, epsPensjon=false, eps2G=false)",
"Response: …
```
> Ta i bruk serviceData fra tjenestepensjon-simulering

- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/SecurityConfiguration.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/egress/EgressAccess.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/egress/EnrichedAuthentication.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/ingress/SecurityLevelFilter.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/tech/security/ingress/impersonal/ImpersonalAccessFilter.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/ansatt/api/AnsattControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/avtale/api/PensjonsavtaleControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/ekskludering/api/EkskluderingControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/omstillingsstoenad/api/OmstillingsstoenadOgGjenlevendeYtelseControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/opptjening/api/FremtidigInntektV2ControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/person/api/PersonControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/simulering/api/SimuleringControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/crypto/api/CryptoControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/security/ingress/SecurityLevelFilterTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/status/StatusControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tech/toggle/api/FeatureToggleControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjon/api/TjenestepensjonControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/tjenestepensjonsimulering/TjenestepensjonSimuleringControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/ufoere/api/UfoerepensjonControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/uttaksalder/api/UttaksalderControllerTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/vedtak/api/VedtakControllerTest.kt
Brukere med strengt fortrolig adresse må logge inn med høyt sikkerhetsnivå (MinID er ikke tilstrekkelig).
Høyt sikkerhetsnivå er en av disse:
- idporten-loa-high
- Level4
MinID har som sikkerhetsnivå en av disse:
- idporten-loa-substantial
- Level3
Denne PR gjør at dette sjekkes i et nytt servlet-filter: `SecurityLevelFilter`.
NB: Brukere med fortrolig adresse (ikke strengt fortrolig) skal kunne bruke MinId.
> PEK-846 Require high security if 'strengt fortrolig adresse'

- src/main/kotlin/no/nav/pensjon/kalkulator/uttaksalder/LavesteUttaksalderService.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/uttaksalder/LavesteUttaksalderServiceTest.kt
'Nærmeste fremtidige alder' er alder på 1. dag av neste måned.
> PEK-957 Fix 'nærmeste fremtidige alder'

- src/main/kotlin/no/nav/pensjon/kalkulator/general/Alder.kt
- src/main/kotlin/no/nav/pensjon/kalkulator/uttaksalder/LavesteUttaksalderService.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/general/AlderTest.kt
- src/test/kotlin/no/nav/pensjon/kalkulator/uttaksalder/LavesteUttaksalderServiceTest.kt
Tidligst mulig uttak (TMU) skal beregnes som alder på nærmeste fremtidige uttaksdato etter minimumsalder.
> PEK-1044 Fix 'nærmeste fremtidige uttaksalder'

- src/main/resources/application.properties
I et forsøk på å unngå `IllegalArgumentException: Request header is too large` økes max header-størrelse på HTTP-requester fra 8KB (Tomcat-default) til 16KB.
> PEK-723 Increase max-http-request-header-size

- .nais/deploy-dev.yml
Tillat alle applikasjoner å snakke til pensjonskalkulator-backend i dev. Slik kan frontend lage testmiljø PR pull-request.
ref. https://github.com/navikt/pensjonskalkulator-frontend/pull/2015
> PEK-1168: Tillat alle applikasjoner i pensjonskalkulator NS å snakke med backend i dev

- .docker/Dockerfile
> I Nav betaler vi for Chainguard images som er minimale images med ekstra sikkerhetstiltak. Her får du distroless images med (nesten alltid) null sårbarheter.
– [Nav Security Playbook: Valg av baseimage](https://sikkerhet.nav.no/docs/sikker-utvikling/baseimages/)
> TPP-18 Use Chainguard Docker image
